//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LSS.Models.LSS_DB_Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class CourseAssessmentMapping
    {
        public string CourseID { get; set; }
        public System.DateTime Year { get; set; }
        public string Semseter { get; set; }
        public int AssessmentID { get; set; }
        public int CLO { get; set; }
        public string SLO { get; set; }
    
        public virtual CLO CLO1 { get; set; }
        public virtual CourseCoordinator CourseCoordinator { get; set; }
        public virtual SLO SLO1 { get; set; }
    }
}
