//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LSS.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class AssessmentPlanforTheStudentLearningOutcomeTechnique
    {
        public string CourseID { get; set; }
        
        [Required]
        [Display(Name = "Date")]
        [DataType(DataType.Date)]
        public System.DateTime Year { get; set; }
        public string Semester { get; set; }
        public bool Midterm_Test { get; set; }
        public bool Final_Exam { get; set; }
        public bool Quiz { get; set; }
        public bool Assignment { get; set; }
        public bool project { get; set; }
        public bool Written_Report { get; set; }
        public bool Oral_Presenation { get; set; }
        public bool Practice_In_The_Lab { get; set; }
        public bool Case_Studdy { get; set; }
        public bool Coruse_Assessment_Survey_By_Students { get; set; }
        public bool Gropu_Discussions { get; set; }
        public bool Students_Interviews { get; set; }
        public string Other { get; set; }
    
        public virtual CourseCoordinator CourseCoordinator { get; set; }
    }
}
