//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LSS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AssessmentSurveyAnswer
    {
        public int Id { get; set; }
        public int QID { get; set; }
        public string Answer { get; set; }
    
        public virtual CourseAssessmentSurvay CourseAssessmentSurvay { get; set; }
    }
}
