//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LSS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AssessmentPlanforTheStudentLearningOutcomeTechnique
    {
        public string CourseID { get; set; }
        public System.DateTime Year { get; set; }
        public string Semester { get; set; }
        public Nullable<bool> Midterm_Test { get; set; }
        public Nullable<bool> Final_Exam { get; set; }
        public Nullable<bool> Quiz { get; set; }
        public Nullable<bool> Assignment { get; set; }
        public Nullable<bool> project { get; set; }
        public Nullable<bool> Written_Report { get; set; }
        public Nullable<bool> Oral_Presenation { get; set; }
        public Nullable<bool> Practice_In_The_Lab { get; set; }
        public Nullable<bool> Case_Studdy { get; set; }
        public Nullable<bool> Coruse_Assessment_Survey_By_Students { get; set; }
        public Nullable<bool> Gropu_Discussions { get; set; }
        public Nullable<bool> Students_Interviews { get; set; }
    
        public virtual CourseCoordinator CourseCoordinator { get; set; }
    }
}
