//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LSS.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class byCompletingThisCourseStudentsAreAbleTo
    {
        [Required]
        [Display(Name = "Course ID")]
        public string CourseID { get; set; }

        [Required]
        public System.DateTime Year { get; set; }

        [Required]
        public string Semester { get; set; }

        public string SLO { get; set; }
        
        [Display(Name = "Aggrement LVL")]
        public string AggrementLVL { get; set; }
    
        public virtual CourseCoordinator CourseCoordinator { get; set; }
    }
}
