//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LSS.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class CourseCoordinator
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CourseCoordinator()
        {
            this.CourseAssessmentMappings = new HashSet<CourseAssessmentMapping>();
            this.CourseAssessmentSurvays = new HashSet<CourseAssessmentSurvay>();
            this.CourseExams = new HashSet<CourseExam>();
            this.CourseTeachingStrategies = new HashSet<CourseTeachingStrategy>();
            this.EnroledStudents = new HashSet<EnroledStudent>();
            this.OtherLecturers = new HashSet<OtherLecturer>();
            this.Schedules = new HashSet<Schedule>();
            this.CourseExamQuestions = new HashSet<CourseExamQuestion>();
        }
    
        public string CourseID { get; set; }
        [Required]
        [Display(Name = "Date")]
        [DataType(DataType.Date)]
        public System.DateTime Year { get; set; }
        public string semester { get; set; }
        public int NoOFStudents { get; set; }
        public string ClassRoom { get; set; }
        public string courseNotAssessedReason_ { get; set; }
        public string DayTime { get; set; }
        public string Coordinator { get; set; }
    
        public virtual ActionsForImprovingTheCourse ActionsForImprovingTheCourse { get; set; }
        public virtual AssessmentPlanforTheStudentLearningOutcomeTechnique AssessmentPlanforTheStudentLearningOutcomeTechnique { get; set; }
        public virtual byCompletingThisCourseStudentsAreAbleTo byCompletingThisCourseStudentsAreAbleTo { get; set; }
        public virtual Course Course { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CourseAssessmentMapping> CourseAssessmentMappings { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CourseAssessmentSurvay> CourseAssessmentSurvays { get; set; }
        public virtual Lecturer Lecturer { get; set; }
        public virtual YearAndSemester YearAndSemester { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CourseExam> CourseExams { get; set; }
        public virtual CourseFileCheckList CourseFileCheckList { get; set; }
        public virtual CourseInformationForm CourseInformationForm { get; set; }
        public virtual CourseReport CourseReport { get; set; }
        public virtual CourseSyllabu CourseSyllabu { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CourseTeachingStrategy> CourseTeachingStrategies { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EnroledStudent> EnroledStudents { get; set; }
        public virtual ineffectiveAssessmentStrategi ineffectiveAssessmentStrategi { get; set; }
        public virtual ineffectiveTeachingStrategi ineffectiveTeachingStrategi { get; set; }
        public virtual isAssessed isAssessed { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OtherLecturer> OtherLecturers { get; set; }
        public virtual ResultOfCourseDirectAssessment ResultOfCourseDirectAssessment { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Schedule> Schedules { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CourseExamQuestion> CourseExamQuestions { get; set; }
    }
}
