//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LSS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CourseExamQuestion
    {
        public int ID { get; set; }
        public int ExamID { get; set; }
        public string QuestionNumber { get; set; }
        public string Question { get; set; }
        public float Weight { get; set; }
    
        public virtual CourseExam CourseExam { get; set; }
    }
}
