//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LSS.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class CourseAssessmentSurvay
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CourseAssessmentSurvay()
        {
            this.AssessmentSurveyAnswers = new HashSet<AssessmentSurveyAnswer>();
        }

        [Required]
        public int ID { get; set; }

        [Required]
        [Display(Name = "Course ID")]
        public string CourseID { get; set; }

        [Required]
        public System.DateTime Year { get; set; }

        [Required]
        public string Semester { get; set; }

        [Required]
        public string Qustion { get; set; }

        [Required]
        [Display(Name = "PI ID")]
        public string PI_ID { get; set; }

        [Required]
        [Display(Name = "SLO ID")]
        public string SLOID { get; set; }

        [Required]
        [Display(Name = "Dept ID")]
        public int DeptID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AssessmentSurveyAnswer> AssessmentSurveyAnswers { get; set; }
        public virtual CourseCoordinator CourseCoordinator { get; set; }
    }
}
