//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LSS.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Course
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Course()
        {
            this.CLOes = new HashSet<CLO>();
            this.Course1 = new HashSet<Course>();
            this.Course11 = new HashSet<Course>();
            this.CourseCoordinators = new HashSet<CourseCoordinator>();
            this.CourseTextBooks = new HashSet<CourseTextBook>();
            this.SLOes = new HashSet<SLO>();
        }
        [Required]
        public string ID { get; set; }

        [Required]
        public string Title { get; set; }

        [Required]
        public string Hours { get; set; }

        public string Designation { get; set; }

        [Display(Name = "Vclass URL")]
        public string VclassURL { get; set; }

        public string Description { get; set; }

        [Display(Name = "Other Online resources")]
        public string Other_Online_resources { get; set; }

        [Display(Name = "Other Required Material")]
        public string Other_Required_Material { get; set; }

        [Display(Name = "pre requisite")]
        public string pre_requisite { get; set; }

        [Display(Name = "co requisite")]
        public string co_requisite { get; set; }

        [Required]
        [Display(Name = "dpt id")]
        public int dptid { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CLO> CLOes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Course> Course1 { get; set; }
        public virtual Course Course2 { get; set; }
        public virtual Department Department { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Course> Course11 { get; set; }
        public virtual Course Course3 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CourseCoordinator> CourseCoordinators { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CourseTextBook> CourseTextBooks { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SLO> SLOes { get; set; }
    }
}
