//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LSS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CourseExamEval
    {
        public int ID { get; set; }
        public int StudentID { get; set; }
        public float Mark { get; set; }
    
        public virtual EnroledStudent EnroledStudent { get; set; }
        public virtual CourseExamQuestion CourseExamQuestion { get; set; }
    }
}
