//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LSS.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class CourseExamEval
    {
        [Required]
        [Display(Name = "Q ID")]
        public int QID { get; set; }

        [Required]
        [Display(Name = "Student ID")]
        public int StudentID { get; set; }

        [Required]
        public float Mark { get; set; }
    
        public virtual EnroledStudent EnroledStudent { get; set; }
        public virtual CourseExamQuestion CourseExamQuestion { get; set; }
    }
}
