//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LSS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EnroledStudent
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public EnroledStudent()
        {
            this.CourseExamEvals = new HashSet<CourseExamEval>();
        }
    
        public int ID { get; set; }
        public string StudentID { get; set; }
        public string CourseID { get; set; }
        public System.DateTime Year { get; set; }
        public string semester { get; set; }
        public Nullable<int> FinalGrade { get; set; }
        public Nullable<int> OtherLecturer { get; set; }
    
        public virtual CourseCoordinator CourseCoordinator { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CourseExamEval> CourseExamEvals { get; set; }
        public virtual OtherLecturer OtherLecturer1 { get; set; }
        public virtual Student Student { get; set; }
    }
}
