//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LSS.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Faculty
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Faculty()
        {
            this.Departments = new HashSet<Department>();
        }

        [Required]
        public int ID { get; set; }

        [Required]
        public string Name { get; set; }

        [Display(Name = "Vice Dean")]
        public string ViceDean { get; set; }

        public string dean { get; set; }

        [Required]
        [Display(Name = "Passing Grade For PI")]
        public int PassingGradeForPI { get; set; }

        [Required]
        [Display(Name = "Passing Grade For Assessment Survey")]
        public float PassingGradeForAssessmentSurvey { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Department> Departments { get; set; }
        public virtual Lecturer Lecturer { get; set; }
        public virtual Lecturer Lecturer1 { get; set; }
    }
}
