//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LSS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ModerationChecklist
    {
        public int ID { get; set; }
        public string CourseID { get; set; }
        public System.DateTime Year { get; set; }
        public string semester { get; set; }
        public string Question { get; set; }
        public bool Answer { get; set; }
        public string commetns { get; set; }
    
        public virtual CourseExam CourseExam { get; set; }
    }
}
