//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LSS.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class OtherLecturer
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public OtherLecturer()
        {
            this.EnroledStudents = new HashSet<EnroledStudent>();
        }
        [Required]
        public int ID { get; set; }

        [Required]
        [Display(Name = "Lecturer ID")]
        public string LecturerID { get; set; }

        [Required]
        [Display(Name = "Course ID")]
        public string CourseID { get; set; }

        [Required]
        public System.DateTime Year { get; set; }

        [Required]
        public string Semester { get; set; }

        [Required]
        [Display(Name = "Day Time")]
        public string DayTime { get; set; }

        [Required]
        [Display(Name = "Class Room")]
        public string ClassRoom { get; set; }

        [Display(Name = "no OF Students")]
        public Nullable<int> noOFStudents { get; set; }
    
        public virtual CourseCoordinator CourseCoordinator { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EnroledStudent> EnroledStudents { get; set; }
        public virtual Lecturer Lecturer { get; set; }
    }
}
