//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LSS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PIAssessment
    {
        public int ID { get; set; }
        public int EnrollmentID { get; set; }
        public int PI { get; set; }
        public string WhereItWasTakenFrom { get; set; }
        public Nullable<float> mark { get; set; }
    
        public virtual EnroledStudent EnroledStudent { get; set; }
        public virtual PI PI1 { get; set; }
    }
}
