//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LSS.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class ResultOfCourseDirectAssessment
    {
        [Required]
        [Display(Name = "Course ID")]
        public string CourseID { get; set; }

        [Required]
        public System.DateTime Year { get; set; }

        [Required]
        public string Semester { get; set; }

        [Required]
        [Display(Name = "Actions Taken")]
        public string ActionsTaken { get; set; }

        [Required]
        public string Observation { get; set; }

        [Required]
        [Display(Name = "Analysis And Justification")]
        public string AnalysisAndJustification { get; set; }

        [Required]
        public string Recommendation { get; set; }
    
        public virtual CourseCoordinator CourseCoordinator { get; set; }
    }
}
