//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LSS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SLO_PEO
    {
        public string SLO { get; set; }
        public string PEO { get; set; }
        public string DeptID { get; set; }
    
        public virtual PEO PEO1 { get; set; }
        public virtual SLO SLO1 { get; set; }
    }
}
