//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LSS.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class SLO_PEO
    {
        [Required]
        [Display(Name = "SLO ID")]
        public string SLOID { get; set; }

        [Required]
        [Display(Name = "PEO ID")]
        public string PEOID { get; set; }

        [Required]
        [Display(Name = "Dept ID")]
        public int DeptID { get; set; }
    
        public virtual PEO PEO { get; set; }
        public virtual SLO SLO { get; set; }
    }
}
